
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow, QPushButton, QMessageBox

from viewwindow import Ui_MainWindow as viewwindow

class Ui_MainWindow(QMainWindow):

    def viewwindow(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = viewwindow()
        self.ui.setupUi(self.window)
        self.window.show()
        self.MainWindow.hide()

    def setupUi(self, MainWindow):
        self.MainWindow = MainWindow
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 450)
        MainWindow.setMinimumSize(QtCore.QSize(800, 450))
        MainWindow.setMaximumSize(QtCore.QSize(800, 450))
        MainWindow.setStyleSheet("background-color: rgb(29, 29, 29);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setEnabled(True)
        self.tableWidget.setGeometry(QtCore.QRect(10, 40, 781, 391))
        self.tableWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableWidget.setFrameShape(QtWidgets.QFrame.Box)
        self.tableWidget.setDragDropOverwriteMode(False)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setGridStyle(QtCore.Qt.CustomDashLine)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(150)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(100)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(True)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(30)
        self.tableWidget.verticalHeader().setHighlightSections(True)
        self.tableWidget.verticalHeader().setSortIndicatorShown(False)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 781, 27))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.addbut = QtWidgets.QPushButton(self.layoutWidget)
        self.addbut.setStyleSheet("background-color: rgb(226, 226, 226);")
        self.addbut.setObjectName("addbut")
        self.horizontalLayout.addWidget(self.addbut)
        self.delbut = QtWidgets.QPushButton(self.layoutWidget)
        self.delbut.setStyleSheet("background-color: rgb(226, 226, 226);")
        self.delbut.setObjectName("delbut")
        self.horizontalLayout.addWidget(self.delbut)
        self.searchbut = QtWidgets.QPushButton(self.layoutWidget)
        self.searchbut.setStyleSheet("background-color: rgb(226, 226, 226);")
        self.searchbut.setObjectName("searchbut")
        self.horizontalLayout.addWidget(self.searchbut)
        self.viewbut = QtWidgets.QPushButton(self.layoutWidget)
        self.viewbut.setStyleSheet("background-color: rgb(226, 226, 226);")
        self.viewbut.setObjectName("viewbut")
        self.viewbut.clicked.connect(self.viewwindow)
        self.horizontalLayout.addWidget(self.viewbut)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.updatebut = QtWidgets.QPushButton(self.layoutWidget)
        self.updatebut.setStyleSheet("background-color: rgb(226, 226, 226);")
        self.updatebut.setObjectName("updatebut")
        self.horizontalLayout_2.addWidget(self.updatebut)
        self.refreshbut = QtWidgets.QPushButton(self.layoutWidget)
        self.refreshbut.setStyleSheet("background-color: rgb(226, 226, 226);")
        self.refreshbut.setObjectName("refreshbut")
        self.horizontalLayout_2.addWidget(self.refreshbut)
        self.displaybut = QtWidgets.QPushButton(self.layoutWidget)
        self.displaybut.setStyleSheet("background-color: rgb(226, 226, 226);")
        self.displaybut.setObjectName("displaybut")
        self.horizontalLayout_2.addWidget(self.displaybut)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Student no."))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Firstname"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Lastname"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Program"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Position"))
        self.addbut.setText(_translate("MainWindow", "Add"))
        self.delbut.setText(_translate("MainWindow", "Delete"))
        self.searchbut.setText(_translate("MainWindow", "Search"))
        self.viewbut.setText(_translate("MainWindow", "View"))
        self.updatebut.setText(_translate("MainWindow", "Update"))
        self.refreshbut.setText(_translate("MainWindow", "Refresh"))
        self.displaybut.setText(_translate("MainWindow", "Display"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
