# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'adminwindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow, QPushButton, QMessageBox

class Ui_MainWindow(QMainWindow):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 450)
        MainWindow.setMinimumSize(QtCore.QSize(800, 450))
        MainWindow.setMaximumSize(QtCore.QSize(800, 450))
        MainWindow.setStyleSheet("background-color: rgb(29, 29, 29);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 40, 151, 391))
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.daybox = QtWidgets.QComboBox(self.frame)
        self.daybox.setGeometry(QtCore.QRect(10, 10, 131, 21))
        self.daybox.setStyleSheet("background-color: rgb(235, 235, 235);")
        self.daybox.setObjectName("daybox")
        self.daybox.addItem("")
        self.daybox.addItem("")
        self.daybox.addItem("")
        self.daybox.addItem("")
        self.daybox.addItem("")
        self.Confirmbut = QtWidgets.QPushButton(self.frame)
        self.Confirmbut.setGeometry(QtCore.QRect(40, 40, 75, 23))
        self.Confirmbut.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-color: rgb(220, 220, 220);")
        self.Confirmbut.setObjectName("Confirmbut")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setEnabled(True)
        self.tableWidget.setGeometry(QtCore.QRect(170, 40, 621, 391))
        self.tableWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableWidget.setFrameShape(QtWidgets.QFrame.Box)
        self.tableWidget.setDragDropOverwriteMode(False)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setGridStyle(QtCore.Qt.CustomDashLine)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(100)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(200)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(True)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(30)
        self.tableWidget.verticalHeader().setHighlightSections(True)
        self.tableWidget.verticalHeader().setSortIndicatorShown(False)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 10, 781, 27))
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.addbut = QtWidgets.QPushButton(self.widget)
        self.addbut.setStyleSheet("background-color: rgb(226, 226, 226);")
        self.addbut.setObjectName("addbut")
        self.horizontalLayout.addWidget(self.addbut)
        self.delbut = QtWidgets.QPushButton(self.widget)
        self.delbut.setStyleSheet("background-color: rgb(226, 226, 226);")
        self.delbut.setObjectName("delbut")
        self.horizontalLayout.addWidget(self.delbut)
        self.delbut_2 = QtWidgets.QPushButton(self.widget)
        self.delbut_2.setStyleSheet("background-color: rgb(226, 226, 226);")
        self.delbut_2.setObjectName("delbut_2")
        self.horizontalLayout.addWidget(self.delbut_2)
        self.delbut_3 = QtWidgets.QPushButton(self.widget)
        self.delbut_3.setStyleSheet("background-color: rgb(226, 226, 226);")
        self.delbut_3.setObjectName("delbut_3")
        self.horizontalLayout.addWidget(self.delbut_3)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.delbut_4 = QtWidgets.QPushButton(self.widget)
        self.delbut_4.setStyleSheet("background-color: rgb(226, 226, 226);")
        self.delbut_4.setObjectName("delbut_4")
        self.horizontalLayout_2.addWidget(self.delbut_4)
        self.delbut_5 = QtWidgets.QPushButton(self.widget)
        self.delbut_5.setStyleSheet("background-color: rgb(226, 226, 226);")
        self.delbut_5.setObjectName("delbut_5")
        self.horizontalLayout_2.addWidget(self.delbut_5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.daybox.setCurrentText(_translate("MainWindow", "Monday"))
        self.daybox.setItemText(0, _translate("MainWindow", "Monday"))
        self.daybox.setItemText(1, _translate("MainWindow", "Tuesday"))
        self.daybox.setItemText(2, _translate("MainWindow", "Wednesday"))
        self.daybox.setItemText(3, _translate("MainWindow", "Thursday"))
        self.daybox.setItemText(4, _translate("MainWindow", "Friday"))
        self.Confirmbut.setText(_translate("MainWindow", "Confirm"))
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Time"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Staffs"))
        self.addbut.setText(_translate("MainWindow", "Add"))
        self.delbut.setText(_translate("MainWindow", "Delete"))
        self.delbut_2.setText(_translate("MainWindow", "Search"))
        self.delbut_3.setText(_translate("MainWindow", "View"))
        self.delbut_4.setText(_translate("MainWindow", "Update"))
        self.delbut_5.setText(_translate("MainWindow", "Refresh"))
import BG_rc
#import Icon_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
